// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGCDQ36v7dPEw2_8CxQbA4qI5nmBLu8Ho',
    appId: '1:435381011779:web:cce0ba293aff48e05f9bf6',
    messagingSenderId: '435381011779',
    projectId: 'friendfinder-b358e',
    authDomain: 'friendfinder-b358e.firebaseapp.com',
    databaseURL: 'https://friendfinder-b358e-default-rtdb.firebaseio.com',
    storageBucket: 'friendfinder-b358e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAH685q7UZWc2Q2WOKXTcdYQmo4od_qhYc',
    appId: '1:435381011779:android:ab2679d9ec9995c15f9bf6',
    messagingSenderId: '435381011779',
    projectId: 'friendfinder-b358e',
    databaseURL: 'https://friendfinder-b358e-default-rtdb.firebaseio.com',
    storageBucket: 'friendfinder-b358e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1yO_MHdmrove9JdYWm2ZMpLb_4uE8ZIw',
    appId: '1:435381011779:ios:ebbdfb69e3bc69b25f9bf6',
    messagingSenderId: '435381011779',
    projectId: 'friendfinder-b358e',
    databaseURL: 'https://friendfinder-b358e-default-rtdb.firebaseio.com',
    storageBucket: 'friendfinder-b358e.appspot.com',
    iosClientId: '435381011779-iul1o095m54o74otqpodnamvtn1d83su.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahallahfriendfinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1yO_MHdmrove9JdYWm2ZMpLb_4uE8ZIw',
    appId: '1:435381011779:ios:ebbdfb69e3bc69b25f9bf6',
    messagingSenderId: '435381011779',
    projectId: 'friendfinder-b358e',
    databaseURL: 'https://friendfinder-b358e-default-rtdb.firebaseio.com',
    storageBucket: 'friendfinder-b358e.appspot.com',
    iosClientId: '435381011779-iul1o095m54o74otqpodnamvtn1d83su.apps.googleusercontent.com',
    iosBundleId: 'com.example.mahallahfriendfinder',
  );
}
